### ISSUE TITLE
Session does not exist when the sip card is open on 2 places with same person

### ISSUE THREAD

**Issue by pergolafabio** [TECH7Fox/Asterisk-integration#12]
as in topic, if 2 same presons are on the same view where sip card is located, only one person can accept the call, i think the first registered user... the second person, when he presses the answer button, nothing happens : 

maybe a feature to check if session exists and then register again?

![image](https://user-images.githubusercontent.com/43251136/146376750-c2a7846d-5f84-417e-a067-1726d918df93.png)

**Comment by TECH7Fox** [comment]
This will be fixed by using pjsip that supports multiple endpoints.
