### ISSUE TITLE
Repository structure for main is not compliant

### ISSUE THREAD

**Issue by Azelphur** [TECH7Fox/Asterisk-integration#28]
When trying to add the repository in HACS, I get an error message "Repository structure for main is not compliant"

![2021-12-24-115923_552x460_escrotum](https://user-images.githubusercontent.com/280694/147350954-f70b558c-dd9c-4342-8b44-807918b89336.png)

**Comment by Azelphur** [comment]
Turns out this is a minor documentation issue, category should be integration, not lovelace

**Comment by TECH7Fox** [comment]
Now fixed. Thanks for reporting! :)
