### ISSUE TITLE
Use packages to build card

### ISSUE THREAD

**Issue by TECH7Fox** [TECH7Fox/Asterisk-integration#35]
Create typescript file and use a npm-publish-github-packages action.

**Comment by felipecrs** [comment]
I found this btw: https://github.com/KTibow/ha-blueprint

But never tested it myself.

**Comment by felipecrs** [comment]
This is also certainly important: https://github.com/hacs/action

**Comment by TECH7Fox** [comment]
interesting, is that also for the card?

I'm thinking about moving the card to HA-SIP and have it generate the typescript file. Because now I'm changing the generated js file which was only a temporary solution.

**Comment by felipecrs** [comment]
> is that also for the card?

Yes but not for Typescript. By the way I found https://github.com/dermotduffy/frigate-hass-card, they upload the .js file in the GitHub Releases.

**Comment by TECH7Fox** [comment]
Tried setting up typescript again, but couldn't get it to work. https://github.com/TECH7Fox/HA-SIP/tree/develop
Will try again tomorrow.

I saw a action that publishes the npm node into github packages. That could be useful.

**Comment by felipecrs** [comment]
AFAIK HACS only supports reading from GitHub Releases, not from packages... but anyway, it should be very easy to do:

https://github.com/softprops/action-gh-release

Something like:

```
- name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: your.js
```

**Comment by TECH7Fox** [comment]
Well, the problem is that the build command doesn't work. Webpack gives this:
```
WARNING in ./src/sipjsclient-card.ts 214:30-44
export 'Web' (imported as 'Web') was not found in 'sip.js/lib/index' (possible exports: name, version)

ERROR in ./node_modules/sip.js/lib/index.js 2:0-44
Module not found: Error: Can't resolve './version' in 'C:\Users\jordy\source\repos\HA-SIP\node_modules\sip.js\lib'
Did you mean 'version.js'?
BREAKING CHANGE: The request './version' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ./src/sipjsclient-card.ts 2:0-39 214:30-44

ERROR in ./node_modules/sip.js/lib/index.js 7:0-22
Module not found: Error: Can't resolve './api' in 'C:\Users\jordy\source\repos\HA-SIP\node_modules\sip.js\lib'
Did you mean 'index.js'?
BREAKING CHANGE: The request './api' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```
etc.

Works in sip.js-master, don't know what I'm missing. Will try the grammer thing next.

**Comment by TECH7Fox** [comment]
Fixed in latest `develop` commit. Will test it in HA.

**Comment by TECH7Fox** [comment]
![image](https://user-images.githubusercontent.com/32220029/148762495-cdcf90c9-ca10-4991-b249-9552e0f91e62.png)

HACS with github releases only work for integration it seems.

**Comment by TECH7Fox** [comment]
It's working now. I just build it before commiting for now.

**Comment by felipecrs** [comment]
The only problem is that users now need to install both the integration and the lovelace card. Making everything in the integration repository would simplify this step.

**Comment by felipecrs** [comment]
I may be able to help you simplify the setup of everything in the integration repo later...

**Comment by TECH7Fox** [comment]
And not everybody wants to use the card with the extension. And it's easier to test, don't need to restart HA every time.

> I may be able to help you simplify the setup of everything in the integration repo later...

That would be very helpful. Even without the card.

**Comment by TECH7Fox** [comment]
I now also see a card which uses a bundle in Github releases.
https://github.com/kalkih/mini-graph-card
```
{
    "name": "mini-graph-card",
    "render_readme": true
}
```

Don't know how that would work but I will try.

**Comment by felipecrs** [comment]
I think the Frigate card is a good example as well: https://github.com/dermotduffy/frigate-hass-card

**Comment by TECH7Fox** [comment]
It's set up and working on [HA-SIP](https://github.com/TECH7Fox/HA-SIP).
