### ISSUE TITLE
Card stops working after adding entity

### ISSUE THREAD

**Issue by stefanschoemaker** [TECH7Fox/Asterisk-integration#38]
After adding my entity the card stops working and just shows a black bar:
![image](https://user-images.githubusercontent.com/10958812/149556577-148a4bbe-21b8-4337-90fa-f6dd80798148.png)

The add-on seems to be working because my Dahua doorbell is connecting, when trying to setup the card there is no log entry in the add-on log.

**Comment by TECH7Fox** [comment]
Hi @stefanschoemaker,

This bug happend to me too, try existing edit mode and refreshing.

The card is currently being worked on and will be moved to [HA-SIP](https://github.com/TECH7Fox/HA-SIP/).
I will make a release when it's working, and announce it on the discord server.

**Comment by stefanschoemaker** [comment]
Using your HA-SIP is working!

Small note, I have to add in sip_custom.conf:

[sipjs-phone](!)
tlsclientmethod=ALL
tlscipher=ALL

to make the iOS app working, probably not a good solution? but it is working now.

**Comment by TECH7Fox** [comment]
> Using your HA-SIP is working!

Nice!

> Small note, I have to add in sip_custom.conf

I will test and include that in the add-on. Thanks! 😄
