### ISSUE TITLE
Remove from resources

### ISSUE THREAD

**Issue by ErnestStaug** [TECH7Fox/Asterisk-integration#40]
Hello,

We should mention if people are using `HA-SIP` card they should remove `sipjs-card.js` of this integration. Or vice versa.
If they use HA-SIP for more up to date things, this integration `.js` sometimes overwrites and asks different card `.yaml` parameters. Both of them clash with each other.

**Comment by TECH7Fox** [comment]
Hi ErnstStaug,

This is indeed a problem. When I continue working on the integration I will remove the card from there.

**Comment by TECH7Fox** [comment]
Fixed with latest update.
