### ISSUE TITLE
UDP protocol

### ISSUE THREAD

**Issue by bart0947** [TECH7Fox/Asterisk-integration#44]
Hey! I have a doorbell in an apartment building, and I need the ability to connect to it, but for this I only need the udp protocol on port 9060, is it possible to implement the ability to select tcp, udp and tcp / udp transport.
Thanks!

**Comment by TECH7Fox** [comment]
This integration connects to a Asterisk server, not a SIP device directly. Could you explain what you mean?

You can choose the protocols in your PBX server that the doorbell connects to.

**Comment by bart0947** [comment]
The doorbell itself works for me using the SIP protocol, the server is not located at my place. I only have a server name with port 9060, login and password to connect. Through the SIP client on the phone, I connect without problems. I would like to implement this connection in HA. But I can only wait for the server using the UDP protocol, if you choose TCP / UDP, then it doesn’t turn on anymore.

**Comment by bart0947** [comment]
![3F7B81D0-271A-48C0-911B-3167252F7301](https://user-images.githubusercontent.com/61836644/155880558-3e76c15a-8be2-4ef7-a12b-494227e400d0.jpeg)
These are my settings

**Comment by TECH7Fox** [comment]
This is to register as a extension right? That's [HA-SIP](https://github.com/TECH7Fox/HA-SIP).

Since you can't access the server and configure the extension, I don't think this will work with the card because it needs a extension configured for wss.

**Comment by bart0947** [comment]
Thanks!
